apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "community.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "community.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ include "community.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-username
      remoteRef:
        key: cicd/community-service/dev
        property: db_username
    - secretKey: db-password
      remoteRef:
        key: cicd/community-service/dev
        property: db_password
    - secretKey: gb-crypto-key
      remoteRef:
        key: cicd/community-service/dev
        property: gb_crypto_key
