apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: community-secrets
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.storeName }}
    kind: {{ .Values.externalSecret.storeKind }}
  target:
    name: community-secrets       # 3번 파일 deployment의 envFrom.secretRef 와 일치
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: db_username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: db_password
    - secretKey: GB_CRYPTO_KEY
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: gb_crypto_key
