apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: community-secrets
  labels:
    app: community
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: community-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-username
      remoteRef:
        key: cicd/community-service/dev
        property: db_username
    - secretKey: COMMUNITY_DB_PASSWORD
      remoteRef:
        key: community-service/dev
        property: db_password
    - secretKey: gb-crypto-key
      remoteRef:
        key: cicd/community-service/dev
        property: gb_crypto_key
