apiVersion: v1
kind: Service
metadata:
  name: community-service
  labels:
    app: community
spec:
  type: {{ .Values.service.type }}
  selector:
    app: community
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
