apiVersion: v1
kind: ConfigMap
metadata:
  name: document-config
data:
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: {{ .Values.config.authIssuerUri | quote }}
  MEMBER_API_BASE_URL: {{ .Values.config.memberApiBaseUrl | quote }}
  SPRING_DATASOURCE_URL: "jdbc:mysql://{{ .Values.config.dbHost }}:{{ .Values.config.dbPort }}/{{ .Values.config.dbName }}?serverTimezone=UTC&characterEncoding=UTF-8"
  SPRING_DATA_REDIS_HOST: {{ .Values.config.redisHost | quote }}
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
