apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: document-secrets
  labels:
    app: document
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.storeName }}
    kind: {{ .Values.externalSecret.storeKind }}
  target:
    name: document-secrets
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: db_username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: db_password
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: document-service/dev
        property: redis_password
