apiVersion: v1
kind: Service
metadata:
  name: document
  labels:
    app: document
spec:
  type: {{ .Values.service.type }}
  selector:
    app: document
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
