apiVersion: v1
kind: ConfigMap
metadata:
  name: member-config
data:
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: {{ .Values.config.authIssuerUri | quote }}
  SPRING_DATASOURCE_URL: "jdbc:mysql://{{ .Values.config.dbHost }}:{{ .Values.config.dbPort }}/{{ .Values.config.dbName }}?serverTimezone=UTC&characterEncoding=UTF-8"
  SPRING_DATA_REDIS_HOST: {{ .Values.config.redisHost | quote }}
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_USERNAME: {{ .Values.config.mailUsername | quote }}
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
  AUTH_IDP_TOKEN_URI: {{ .Values.config.authTokenUri | quote }}
  AUTH_IDP_CLIENT_ID: {{ .Values.config.authClientId | quote }}
  AUTH_IDP_API_BASE_URI: {{ .Values.config.authApiBaseUri | quote }}
  WALLET_API_BASE_URL: {{ .Values.config.walletApiBaseUrl | quote }}
