apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: member-secrets
  labels:
    app: member
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.storeName }}
    kind: {{ .Values.externalSecret.storeKind }}
  target:
    name: member-secrets
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: db_username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: db_password
    - secretKey: GB_CRYPTO_KEY
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: gb_crypto_key
    - secretKey: SPRING_MAIL_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: mail_password
    - secretKey: AUTH_IDP_ADMIN_TOKEN
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: auth_admin_token
