env: stage
namespace: sb-stage-app-ns
secretBackend: aws
springProfilesActive: stage

image:
  repository: harbor.sb.fisa/global_bridge/member
  tag: "2"
  pullPolicy: IfNotPresent

replicaCount: 2

imagePullSecrets:
  - name: harbor-dockercfg

service:
  type: ClusterIP
  port: 8081
  containerPort: 8081

config:
  # ⚠ stage 검증 한정 (자동 스키마 생성). prod는 validate + 마이그레이션 (Flyway/Liquibase) 으로 전환할 것.
  ddlAuto: "update"
  # redisHost 없음 → ConfigMap이 redis host/port 안 넣음. REDIS_HOST/PORT는 SM ExternalSecret에서 주입
  mailUsername: "sangam.beavers@gmail.com"
  walletApiBaseUrl: "http://wallet.sb-stage-app-ns.svc.cluster.local:8084"
  appPasswordResetBaseUrl: "https://d3dbftmbedkk3p.cloudfront.net/reset-password"   # TODO 클라우드 프론트

externalSecret:
  refreshInterval: 1h
  smDbPath: sb/stage/member/db
  smRedisPath: sb/stage/redis/auth
  psPrefix: /sb/stage/member
  psKafkaBootstrapServers: /sb/stage/kafka/bootstrap_servers
