# 컨테이너 이미지
image:
  repository: harbor.sb.fisa/global_bridge/member
  tag: "7"
  pullPolicy: IfNotPresent
# Pod 개수
replicaCount: 1
# Harbor 사설 레지스트리 인증
imagePullSecrets:
  - name: harbor-dockercfg
# Spring server.port = 8081
service:
  port: 8081
  containerPort: 8081
  type: ClusterIP
# 어느 환경에서 도는지
springProfilesActive: dev
# 평범한 설정값 (ConfigMap으로 주입)
config:
  authIssuerUri: "https://sso.sb.fisa/application/o/gb-backend/"
  dbHost: "mysql-lb.gb-dev.svc.cluster.local"
  dbPort: "3306"
  dbName: "member_db"
  redisHost: "redis.gb-dev.svc.cluster.local"
  mailUsername: "sangam.beavers@gmail.com"
  authTokenUri: "https://sso.sb.fisa/application/o/token/"
  authClientId: "gzoLbbd9iqqlGEPjdQAUjB9OjWL0wklVNC0u7EFm"
  authApiBaseUri: "https://sso.sb.fisa/api/v3"
  walletApiBaseUrl: "http://wallet.gb-dev.svc.cluster.local:8084"
  appPasswordResetBaseUrl: "https://app.dev.fisa/reset-password"
  kafkaBootstrapServers: "gb-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
  ddlAuto: "update"
# 컨테이너 리소스 (requests/limits) — env별 override 가능
resources:
  requests:
    memory: 768Mi
    cpu: 250m
  limits:
    memory: 1.5Gi
    cpu: "1"
# Vault에서 가져올 비밀값 경로
externalSecret:
  refreshInterval: 1h
  storeName: vault-backend
  storeKind: ClusterSecretStore
  vaultPath: "member-service/dev"
