apiVersion: v1
kind: Service
metadata:
  name: monitoring
  labels:
    app: monitoring
spec:
  type: {{ .Values.service.type }}
  selector:
    app: monitoring
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
