{{- if eq .Values.secretBackend "vault" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-admin-secrets
  labels:
    app: app-admin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: app-admin-secrets
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: app-admin-service/dev
        property: db_username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: app-admin-service/dev
        property: db_password
{{- end }}
